### ISSUE TITLE
after dropping the previous element with hover is kep in that state although it was draged elsewhere

### ISSUE THREAD

**Issue by yoshrat** [brimdata/react-arborist#122]
You can see it if you add at cities demo a :hover style to css of div role="treeitem" 
```css
.cities_row__th1bg:hover {
    background: aqua;
}
```

Then after dropping an element if you don't move the mouse you'll see the wrong element is in hover state.
In our case the hover state is also used for some inner logic and is broken
